version: "3.3"

services:

  web:
    build: .
    image: mayhem.cat
    expose:
      - "3031"
    volumes:
      - .:/code/mayhem.cat:z
    environment:
      - VIRTUAL_HOST=test.mayhem.cat
      - LETSENCRYPT_HOST=test.mayhem.cat
      - LETSENCRYPT_EMAIL=mayhem@gmail.com

networks:
  default:
    name: nginx-proxy
    external: true
